/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.saar.coli.ccgparser;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Joiner;
import de.saar.coli.ccgparser.rules.CombinatoryRule;
import de.saar.coli.ccgparser.screenimage.ScreenImage;
import de.up.ling.tree.Tree;
import de.up.ling.tree.TreePanel;
import me.tongfei.progressbar.ProgressBar;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Locale;

public class App {
    private static class PrintingStatisticsListener implements Parser.StatisticsListener  {
        private PrintWriter pw;
        private int numSentences = 0;

        public PrintingStatisticsListener(String filename) throws IOException {
            this.pw = new PrintWriter(new FileWriter(filename));
            pw.printf("ID\tSentence\tLength\tTime (ms)\tParsed");
            for(CombinatoryRule rule : Parser.COMBINATORY_RULES ) {
                pw.printf("\t%s", rule.getSymbol());
            }
            pw.println();
        }

        @Override
        public void accept(Parser.SentenceStatistics stats) {
            pw.printf("%d\t", numSentences++);
            pw.printf(Locale.US, "%s\t%d\t%.2f\t%s", stats.sentence, stats.length, stats.parsingTimeNano/1000000.0, Boolean.toString(stats.couldParse));
            for(CombinatoryRule rule : Parser.COMBINATORY_RULES ) {
                pw.printf("\t%d", stats.ruleCounts.get(rule));
            }
            pw.println();
        }

        @Override
        public void close() {
            pw.close();
        }
    }

    private static final String PARSES_FILENAME = "parses.txt";
    private static final String STATISTICS_FILENAME = "statistics.tsv";

    private static void writeToFile(Tree<String> tree, File file) throws IOException {
        TreePanel<String> panel = new TreePanel<>(tree);

        // This is a bit weird, but we have to draw the image twice: once to determine
        // its actual size, and then to actually draw it into an image of that size.
        BufferedImage image = ScreenImage.createImage(panel);
        panel.setSize(panel.getPreferredSize());
        image = ScreenImage.createImage(panel);

        ImageIO.write(image, "png", file);
    }

    public static void main(String[] args) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        String supertagsFilename = args[0];
        String imageDirectory = args.length > 1 ? args[1] : null;

        if( imageDirectory != null ) {
            // create directory if needed
            Path dirPath = Files.createDirectories(Paths.get(imageDirectory));

            // delete all files in the directory
            for(File file: dirPath.toFile().listFiles()) {
                if (!file.isDirectory()) {
                    file.delete();
                }
            }
        }

        System.err.printf("Reading supertags from %s.\n", supertagsFilename);
        WordWithSupertags[][] allTaggedSentences = mapper.readValue(new File(supertagsFilename), WordWithSupertags[][].class);

        // ASSUMPTION - supertags for each word are presented in order of descending score (best first)
        for( WordWithSupertags[] sentence : allTaggedSentences ) {
            for( WordWithSupertags word : sentence ) {
                int i = 0;
                for( SupertagWithScore tag : word.supertags ) {
                    tag.setPositionInSupertagList(i++);
                }
            }
        }

        UnaryRules unaryRules = UnaryRules.load(new File("unary_rules.txt"));

        int numSentences = 0;
        int parsedSentences = 0;
        PrintWriter pw = new PrintWriter(new FileWriter(PARSES_FILENAME));
        Parser.StatisticsListener listener = new PrintingStatisticsListener("statistics.tsv");


        try (ProgressBar pb = new ProgressBar("Parsing", allTaggedSentences.length)) {
            for (WordWithSupertags[] sentence : allTaggedSentences) {
//                System.err.printf("[%04d] %.100s\n", numSentences+1, Joiner.on(" ").join(sentence));
                Parser parser = new Parser(sentence, unaryRules);
                parser.addStatisticsListener(listener);
                Tree<String> parseTree = parser.parse();

                if( parseTree != null ) {
                    if( imageDirectory != null ) {
                        writeToFile(parseTree, new File(imageDirectory, String.format("tree%04d.png", numSentences)));
                    }
                }

                numSentences++;
                if (parseTree != null) {
                    parsedSentences++;
                }

                pw.println(parseTree == null ? "<null>" : parseTree.toString());
                pb.step();
            }
        }

        pw.close();
        listener.close();

        System.err.printf("\nManaged to parse %d out of %d sentences (%.1f%%).\n", parsedSentences, numSentences, ((double) parsedSentences * 100)/numSentences);
        System.err.printf("Parses are in %s, statistics are in %s.\n", PARSES_FILENAME, STATISTICS_FILENAME);

//
//
//        Tree<String> parseTree = null;
//
//        for( int i = 0; i < 1; i++ ) {
//            long start = System.nanoTime();
//            Parser parser = new Parser(allTaggedSentences[0], unaryRules);
//            parseTree = parser.parse();
//            long end = System.nanoTime();
//            System.err.printf("%d μs\n", (end-start)/1000);
//        }
//
//        System.err.println(parseTree);
//        if( parseTree != null ) {
//            parseTree.draw().setVisible(true);
//        }
    }
}
